language: node_js
node_js:
- '4'
before_install:
- npm install
- npm install -g typescript@2.3.2
- tsc
deploy:
  provider: npm
  email: work@denwilliams.net
  on:
    tags: true
    repo: denwilliams/homenet-plugin-datadog
